In [1]:
import pandas as pd

In [3]:
#Series 
import pandas as pd 
data =[1,2,3,4,5]
series = pd.Series(data)
print("Series\n",series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [5]:
##Series from Dictonary
data = {'a':1,'b':2,'c':3}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [6]:
data=[10,20,30]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [9]:
#DataFrame: It will be having multiple rows and colums . Ex:database or excel
import pandas as pd
data={
    'Name':['Jon','Jack','Berlin'],
    'Age':[25,30,45],
    'City':['Bangalore','NewYork','Florida']
}
df=pd.DataFrame(data)
print(type(df))

<class 'pandas.DataFrame'>

In [10]:
#DatFrame from a list of Dictionaries

data =[
    {'Name':'Jon','Age':32,'City':'Bangalore'},
    {'Name':'Kridh','Age':34,'City':'Bangalore'},
    {'Name':'Kav','Age':38,'City':'Bangalore'},
    {'Name':'krish','Age':36,'City':'Bangalore'},
]

In [11]:
df = pd.read_csv('example_data.csv')
df.head(3)

   StudentID    Name  Age       City            Course  Score
0          1   Sneha   19  Bangalore  Machine Learning     86
1          2  Ishaan   22     Mumbai              Java     51
2          3  Ishaan   23       Pune   Web Development     86

In [12]:
df

    StudentID    Name  Age       City            Course  Score
0           1   Sneha   19  Bangalore  Machine Learning     86
1           2  Ishaan   22     Mumbai              Java     51
2           3  Ishaan   23       Pune   Web Development     86
3           4   Rahul   21    Chennai   Web Development     53
4           5   Rohan   24      Delhi      Data Science     67
..        ...     ...  ...        ...               ...    ...
95         96   Anika   24       Pune   Web Development     82
96         97    Diya   20    Chennai            Python     58
97         98   Meera   18     Mumbai   Web Development     69
98         99   Kavya   23  Bangalore   Web Development     80
99        100   Sneha   25  Bangalore               DSA     65

[100 rows x 6 columns]